language: node_js
node_js:
  - "6.10"
cache:
  directories:
    - "node_modules"
    - '$HOME/.sonar/cache'
script:
  - npm install
  - npm test
  - sonar-scanner
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "codegovapi"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
  
    