version: '3'
services:
  api:
    build: .
    image: 'codegov/code-gov-api:latest'
    container_name: 'code-gov-api'
    ports:
      - "8080:3001/tcp"
    environment:
      - NEW_RELIC_KEY='not_a_key'
      - GITHUB_API_KEY='not-a-key'
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASSWORD=changeme
      - NODE_ENV='production'
    depends_on:
      - elasticsearch
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.9"
    container_name: 'code-gov-data'